/*
 * Copyright 2016 Huawei Technologies Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.openo.sdno.vxlan.mockdata;

public class OverlayVpnData {

    public static String getCreateFullMeshVpnDataString() {
        return "{" + "   \"tenantId\" : \"12345\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{"
                + "           \"tenantId\" : \"12345\"," + "           \"name\" : \"site1-to-dc1\","
                + "           \"description\" : \"Update test 111\"," + "           \"operStatus\" : \"none\","
                + "           \"adminStatus\" : \"inactive\"," + "           \"topology\" : \"full_mesh\","
                + "           \"technology\" : \"vxlan\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc1 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"port\","
                + "                   \"neId\" : \"1111\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"auuidiusdf\\\"]\","
                + "                   \"endpointList\" : [\"1.2.3.4/24\"],"
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc2 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"port\","
                + "                   \"endpoints\" : \"[\\\"afdfadsfadsfasdf\\\"]\","
                + "                   \"endpointList\" : [\"2.2.3.4/24\"]," + "                   \"neId\" : \"1111\","
                + "                   \"deviceId\" : \"ne2\"," + "                   \"gatewayId\" : \"\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"vxlanMappingPolicy\" : {" + "               \"arpProxy\" : \"true\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"vxlan\"," + "               \"arpBroadcastSuppress\" : \"true\","
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }

    public static String getCreateHubSpokeVpnDataString() {
        return "{" + "   \"tenantId\" : \"12345\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{"
                + "           \"tenantId\" : \"12345\"," + "           \"name\" : \"site1-to-dc1\","
                + "           \"description\" : \"Update test 111\"," + "           \"operStatus\" : \"none\","
                + "           \"adminStatus\" : \"inactive\"," + "           \"topology\" : \"hub_spoke\","
                + "           \"technology\" : \"gre_over_ipsec\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc1 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"cidr\","
                + "                   \"neId\" : \"1111\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"1.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"1.2.3.4/24\"],"
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc2 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"cidr\","
                + "                   \"endpoints\" : \"[\\\"2.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"2.2.3.4/24\"]," + "                   \"neId\" : \"2222\","
                + "                   \"deviceId\" : \"ne2\"," + "                   \"gatewayId\" : \"\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"greMappingPolicy\" : {" + "               \"tenantId\" : \"12345\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"gre\"," + "               \"greTunnelKey\" : \"11111\","
                + "               \"authMode\" : \"PSK\"," + "               \"psk\" : \"erwe!23\","
                + "               \"ikePolicyId\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\","
                + "               \"ipsecPolicyId\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\","
                + "               \"ikePolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ikepolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : \"sha1\","
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"ikeVersion\" : \"v2\","
                + "                   \"id\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\"" + "               },"
                + "               \"ipSecPolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ipsecpolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : null,"
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"transformProtocol\" : \"esp\","
                + "                   \"encapsulationMode\" : \"transport\","
                + "                   \"id\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\"" + "               },"
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null," + "           \"vxlanMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }

    public static String getUpdateVpnDataString() {
        return "{" + "   \"tenantId\" : \"12345\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{"
                + "           \"tenantId\" : \"12345\"," + "           \"name\" : \"site1-to-dc1\","
                + "           \"description\" : \"Update test 111\"," + "           \"operStatus\" : \"none\","
                + "           \"adminStatus\" : \"inactive\"," + "           \"topology\" : \"full_mesh\","
                + "           \"technology\" : \"gre_over_ipsec\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc1 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"cidr\","
                + "                   \"neId\" : \"1111\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"1.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"1.2.3.4/24\"],"
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc1 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"modifyMask\" : \"add\","
                + "                   \"type\" : \"cidr\"," + "                   \"neId\" : \"3333\","
                + "                   \"deviceId\" : \"ne3\","
                + "                   \"endpoints\" : \"[\\\"3.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"3.2.3.4/24\"],"
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-facgsdfqeb04\"" + "               },{"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc2 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"cidr\","
                + "                   \"endpoints\" : \"[\\\"2.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"2.2.3.4/24\"]," + "                   \"neId\" : \"2222\","
                + "                   \"deviceId\" : \"ne2\"," + "                   \"gatewayId\" : \"\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"greMappingPolicy\" : {" + "               \"tenantId\" : \"12345\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"gre\"," + "               \"greTunnelKey\" : \"11111\","
                + "               \"authMode\" : \"PSK\"," + "               \"psk\" : \"erwe!23\","
                + "               \"ikePolicyId\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\","
                + "               \"ipsecPolicyId\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\","
                + "               \"ikePolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ikepolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : \"sha1\","
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"ikeVersion\" : \"v2\","
                + "                   \"id\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\"" + "               },"
                + "               \"ipSecPolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ipsecpolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : null,"
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"transformProtocol\" : \"esp\","
                + "                   \"encapsulationMode\" : \"transport\","
                + "                   \"id\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\"" + "               },"
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null," + "           \"vxlanMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }

    public static String getDeployEpgDataString() {
        return "{" + "   \"tenantId\" : \"tenantid\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{"
                + "           \"tenantId\" : \"tenantid\"," + "           \"name\" : \"site1-to-dc1\","
                + "           \"description\" : \"Update test 111\"," + "           \"operStatus\" : \"none\","
                + "           \"adminStatus\" : \"inactive\"," + "           \"topology\" : \"full_mesh\","
                + "           \"technology\" : \"vxlan\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"tenantid\","
                + "                   \"name\" : \"dc1 web servers\"," + "                   \"description\" : null,"
                + "                   \"operStatus\" : \"none\"," + "                   \"adminStatus\" : \"inactive\","
                + "                   \"modifyMask\" : \"deploy\"," + "                   \"type\" : \"port\","
                + "                   \"neId\" : \"neid1\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"ltpid1\\\"]\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"neid1\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"tenantid\","
                + "                   \"name\" : \"dc2 web servers\"," + "                   \"description\" : null,"
                + "                   \"operStatus\" : \"none\"," + "                   \"adminStatus\" : \"inactive\","
                + "                   \"type\" : \"port-and-vlan\","
                + "                   \"endpoints\" : \"[\\\"ltpid2/1\\\"]\","
                + "                   \"neId\" : \"neid2\"," + "                   \"deviceId\" : \"ne2\","
                + "                   \"gatewayId\" : \"\"," + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"neid2\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"vxlanMappingPolicy\" : {" + "               \"arpProxy\" : \"true\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"vxlan\"," + "               \"arpBroadcastSuppress\" : \"true\","
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }

    public static String getUndeployVpnDataString() {
        return "{" + "   \"tenantId\" : \"12345\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"modifyMask\" : \"UNDEPLOY\","
                + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{" + "           \"tenantId\" : \"12345\","
                + "           \"name\" : \"site1-to-dc1\"," + "           \"description\" : \"Update test 111\","
                + "           \"operStatus\" : \"none\"," + "           \"adminStatus\" : \"inactive\","
                + "           \"topology\" : \"full_mesh\"," + "           \"technology\" : \"gre_over_ipsec\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc1 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"cidr\","
                + "                   \"neId\" : \"1111\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"1.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"1.2.3.4/24\"],"
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc2 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\","
                + "                   \"modifyMask\" : \"deploy\"," + "                   \"type\" : \"cidr\","
                + "                   \"endpoints\" : \"[\\\"2.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"2.2.3.4/24\"]," + "                   \"neId\" : \"2222\","
                + "                   \"deviceId\" : \"ne2\"," + "                   \"gatewayId\" : \"\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"greMappingPolicy\" : {" + "               \"tenantId\" : \"12345\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"gre\"," + "               \"greTunnelKey\" : \"11111\","
                + "               \"authMode\" : \"PSK\"," + "               \"psk\" : \"erwe!23\","
                + "               \"ikePolicyId\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\","
                + "               \"ipsecPolicyId\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\","
                + "               \"ikePolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ikepolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : \"sha1\","
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"ikeVersion\" : \"v2\","
                + "                   \"id\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\"" + "               },"
                + "               \"ipSecPolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ipsecpolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : null,"
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"transformProtocol\" : \"esp\","
                + "                   \"encapsulationMode\" : \"transport\","
                + "                   \"id\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\"" + "               },"
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null," + "           \"vxlanMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }

    public static String getUndeployConnDataString() {
        return "{" + "   \"tenantId\" : \"12345\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{"
                + "           \"tenantId\" : \"12345\"," + "           \"name\" : \"site1-to-dc1\","
                + "           \"description\" : \"Update test 111\"," + "           \"operStatus\" : \"none\","
                + "           \"adminStatus\" : \"inactive\"," + "   \"modifyMask\" : \"UNDEPLOY\","
                + "           \"topology\" : \"full_mesh\"," + "           \"technology\" : \"gre_over_ipsec\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc1 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\"," + "                   \"type\" : \"cidr\","
                + "                   \"neId\" : \"1111\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"1.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"1.2.3.4/24\"],"
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"12345\"," + "                   \"name\" : \"dc2 web servers\","
                + "                   \"description\" : null," + "                   \"operStatus\" : \"none\","
                + "                   \"adminStatus\" : \"inactive\","
                + "                   \"modifyMask\" : \"deploy\"," + "                   \"type\" : \"cidr\","
                + "                   \"endpoints\" : \"[\\\"2.2.3.4/24\\\"]\","
                + "                   \"endpointList\" : [\"2.2.3.4/24\"]," + "                   \"neId\" : \"2222\","
                + "                   \"deviceId\" : \"ne2\"," + "                   \"gatewayId\" : \"\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"greMappingPolicy\" : {" + "               \"tenantId\" : \"12345\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"gre\"," + "               \"greTunnelKey\" : \"11111\","
                + "               \"authMode\" : \"PSK\"," + "               \"psk\" : \"erwe!23\","
                + "               \"ikePolicyId\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\","
                + "               \"ipsecPolicyId\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\","
                + "               \"ikePolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ikepolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : \"sha1\","
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"ikeVersion\" : \"v2\","
                + "                   \"id\" : \"2dbbdef5-3643-4111-a44f-fb539d9ae6a5\"" + "               },"
                + "               \"ipSecPolicy\" : {" + "                   \"tenantId\" : \"12345\","
                + "                   \"name\" : \"ipsecpolicy1\"," + "                   \"description\" : null,"
                + "                   \"authAlgorithm\" : null,"
                + "                   \"encryptionAlgorithm\" : \"aes-128\","
                + "                   \"pfs\" : \"Group5\"," + "                   \"lifeTime\" : \"3600\","
                + "                   \"transformProtocol\" : \"esp\","
                + "                   \"encapsulationMode\" : \"transport\","
                + "                   \"id\" : \"c6784276-8b00-4ed1-93f2-11c26197c044\"" + "               },"
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null," + "           \"vxlanMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }

    public static String getUndeployEpgDataString() {
        return "{" + "   \"tenantId\" : \"tenantid\"," + "   \"name\" : \"vpn1\","
                + "   \"description\" : \"VPN for customer1.\"," + "   \"operStatus\" : \"none\","
                + "   \"adminStatus\" : \"inactive\"," + "   \"connectionIds\" : null," + "   \"vpnConnections\" : [{"
                + "           \"tenantId\" : \"tenantid\"," + "           \"name\" : \"site1-to-dc1\","
                + "           \"description\" : \"Update test 111\"," + "           \"operStatus\" : \"none\","
                + "           \"adminStatus\" : \"inactive\"," + "           \"topology\" : \"full_mesh\","
                + "           \"technology\" : \"vxlan\","
                + "           \"compositeVpnId\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\","
                + "           \"mappingPolicyId\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\","
                + "           \"epgIds\" : null," + "           \"endpointGroups\" : [{"
                + "                   \"tenantId\" : \"tenantid\","
                + "                   \"name\" : \"dc1 web servers\"," + "                   \"description\" : null,"
                + "                   \"operStatus\" : \"none\"," + "                   \"adminStatus\" : \"inactive\","
                + "                   \"modifyMask\" : \"undeploy\"," + "                   \"type\" : \"port\","
                + "                   \"neId\" : \"neid1\"," + "                   \"deviceId\" : \"ne1\","
                + "                   \"endpoints\" : \"[\\\"ltpid1\\\"]\","
                + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"2d2b7f76-f42f-4997-b3e2-faca89827b04\"" + "               }, {"
                + "                   \"tenantId\" : \"tenantid\","
                + "                   \"name\" : \"dc2 web servers\"," + "                   \"description\" : null,"
                + "                   \"operStatus\" : \"none\"," + "                   \"adminStatus\" : \"inactive\","
                + "                   \"type\" : \"port-and-vlan\","
                + "                   \"endpoints\" : \"[\\\"ltpid2/1\\\"]\","
                + "                   \"neId\" : \"neid2\"," + "                   \"deviceId\" : \"ne2\","
                + "                   \"gatewayId\" : \"\"," + "                   \"topologyRole\" : \"none\","
                + "                   \"connectionId\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\","
                + "                   \"qosPolicyId\" : null," + "                   \"gateway\" : {"
                + "                       \"tenantId\" : \"12345\","
                + "                       \"name\" : \"Site1 VPN Gateway\","
                + "                       \"description\" : null,"
                + "                       \"ipAddress\" : \"10.12.137.1\","
                + "                       \"neId\" : \"26a79807-65d0-414d-bc1f-c1f88cdb7e6e\","
                + "                       \"id\" : \"6699a6dc-6072-4c46-9e19-b13b2733e61d\"" + "                   },"
                + "                   \"id\" : \"8ead66e9-3e16-4f75-8c47-5677eeec7a74\"" + "               }"
                + "           ]," + "           \"vxlanMappingPolicy\" : {" + "               \"arpProxy\" : \"true\","
                + "               \"name\" : \"gre vpn mapping policy1\"," + "               \"description\" : null,"
                + "               \"type\" : \"vxlan\"," + "               \"arpBroadcastSuppress\" : \"true\","
                + "               \"id\" : \"b618b6e1-4096-4423-a2b3-f55ef97f34c6\"" + "           },"
                + "           \"ipsecMappingPolicy\" : null,"
                + "           \"id\" : \"37172b6f-105b-4042-acc8-5ef95aeca88e\"" + "       }" + "   ],"
                + "   \"id\" : \"96a02ef3-8c61-4f0d-afd8-fb39c7dd6e9d\"" + "}";
    }
}
